name: crypto_app
description: Crypto App.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  file_picker: ^6.1.1
  font_awesome_flutter: ^10.6.0
  get_it: ^7.6.4
  iconly: ^1.0.1
  image_picker: ^1.0.4
  intl: ^0.18.1
  lottie: ^2.7.0
  open_file: ^3.3.2
  path_provider: ^2.1.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  swipe_to: ^1.0.2
  url_launcher: ^6.2.1
  youtube_metadata: ^1.0.1
  video_thumbnail: ^0.5.3
  chewie: ^1.7.1
  http: ^0.13.6
  dio: ^5.3.3
  timezone: ^0.9.2
  google_nav_bar: ^5.0.6
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  date_picker_timeline: ^1.2.5
  easy_date_timeline: ^1.0.2
  board_datetime_picker: ^1.3.1
  fl_chart: 0.60.0
  toggle_switch: ^2.1.0
  flutter_spinkit: ^5.2.0
  flutter_native_splash: ^2.3.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  very_good_analysis: ^5.1.0
  bloc_test: ^9.1.5
  mocktail: ^1.0.1

flutter:
  uses-material-design: true
